spring:
   kafka:
      bootstrap-servers: 10.32.26.20:9090,10.32.26.20:9091,10.32.26.20:9092
      producer:
         batch-size: 16384
         buffer-memory: 33554432
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
         group-id: test-consumer-group
         auto-offset-reset: earliest
         enable-auto-commit: true
         auto-commit-interval: 100
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
